
BLENDER="C:\Program Files\Blender Foundation\Blender 5.2\blender.exe"
DIST=../dist

all : \
    $(DIST)/hexapod.pnct \
    $(DIST)/hexapod.scene \
    $(DIST)/dragon_egg.pnct \

$(DIST)/hexapod.scene : hexapod.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "hexapod.blend:Main" "$(DIST)/hexapod.scene"

$(DIST)/hexapod.pnct : hexapod.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "hexapod.blend:Main" "$(DIST)/hexapod.pnct" 

$(DIST)/dragon_egg.pnct : dragon_egg.blend export-meshes.py
	$(BLENDER) --background --python export-meshes.py -- "dragon_egg.blend" "$(DIST)/dragon_egg.pnct" 
